services:
  - type: web
    name: backend
    env: node
    rootDir: ./apps/backend
    buildCommand: |
      pnpm install
      pnpm --filter @repo/db prisma generate
      pnpm --filter ./apps/backend run build
    startCommand: pnpm --filter ./apps/backend run start
    plan: starter
    autoDeploy: true
