services:
  - type: web
    name: alumni-backend
    runtime: node
    rootDir: .
    buildCommand: |
      pnpm install -w --frozen-lockfile
      pnpm --filter @repo/db exec prisma generate
      pnpm turbo run build --filter=@repo/db...
      pnpm turbo run build --filter=backend...

    startCommand: pnpm --filter backend run start
    plan: free
    buildFilter:
      paths:
        - apps/backend/**/*
        - packages/db/**/*
        - packages/ui/**/*
        - packages/zustand/**/*
