services:
  - type: web
    name: backend
    env: node
    rootDir: .
    buildCommand: |
      pnpm install --frozen-lockfile
      pnpm --filter @repo/db prisma generate
      pnpm --filter backend run build
    startCommand: pnpm --filter backend run start
    plan: starter
    autoDeploy: true